
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace LucidHR.Models
{

using System;
    using System.Collections.Generic;
    
public partial class Employee
{

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public Employee()
    {

        this.Attendances = new HashSet<Attendance>();

        this.Departments = new HashSet<Department>();

        this.Expenses = new HashSet<Expens>();

        this.LeaveRequests = new HashSet<LeaveRequest>();

        this.Users = new HashSet<User>();

    }


    public int Id { get; set; }

    public string Name { get; set; }

    public string Surname { get; set; }

    public Nullable<decimal> Salary { get; set; }

    public string Phone { get; set; }

    public Nullable<System.DateTime> JoinDate { get; set; }

    public Nullable<int> RoleId { get; set; }

    public Nullable<bool> Gender { get; set; }

    public string Email { get; set; }

    public string Facebook { get; set; }

    public string Twitter { get; set; }

    public string Linkedin { get; set; }

    public Nullable<decimal> HRA { get; set; }

    public Nullable<decimal> Bonus { get; set; }

    public Nullable<decimal> Conveyance { get; set; }

    public Nullable<decimal> OtherAllowances { get; set; }

    public Nullable<decimal> TDS { get; set; }

    public Nullable<decimal> ESI { get; set; }

    public Nullable<decimal> ProvidentFund { get; set; }

    public Nullable<decimal> BankLoan { get; set; }

    public Nullable<decimal> therDeductions { get; set; }

    public string Profile { get; set; }

    public string Instagram { get; set; }



    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<Attendance> Attendances { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<Department> Departments { get; set; }

    public virtual Role Role { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<Expens> Expenses { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<LeaveRequest> LeaveRequests { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<User> Users { get; set; }

}

}
