
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace LucidHR.Models
{

using System;
    using System.Collections.Generic;
    
public partial class Event
{

    public int Id { get; set; }

    public string Title { get; set; }

    public string Desc { get; set; }

    public string Lacation { get; set; }

    public Nullable<System.DateTime> StartDate { get; set; }

    public Nullable<System.DateTime> EndDate { get; set; }

    public Nullable<System.DateTime> StartTime { get; set; }

    public System.DateTime EndTime { get; set; }

    public Nullable<int> TypeId { get; set; }



    public virtual EventType EventType { get; set; }

}

}
