
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace LucidHR.Models
{

using System;
    using System.Collections.Generic;
    
public partial class Expens
{

    public int Id { get; set; }

    public string Item { get; set; }

    public int Count { get; set; }

    public int OrderBy { get; set; }

    public string From { get; set; }

    public System.DateTime Date { get; set; }

    public bool Status { get; set; }

    public decimal Price { get; set; }

    public int PaymentsTypeId { get; set; }



    public virtual PaymentType PaymentType { get; set; }

    public virtual Employee Employee { get; set; }

}

}
