
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace LucidHR.Models
{

using System;
    using System.Collections.Generic;
    
public partial class Invoice
{

    public int Id { get; set; }

    public int Number { get; set; }

    public int ClientId { get; set; }

    public System.DateTime Date { get; set; }

    public int PaymentTypeId { get; set; }

    public bool Status { get; set; }

    public decimal Amount { get; set; }



    public virtual Client Client { get; set; }

    public virtual PaymentType PaymentType { get; set; }

}

}
